// =============================================================================
// src/database/migrations/1700000000000-InitialSchema.ts
// BlockLand Zimbabwe — Initial Database Migration
// =============================================================================
//
// PURPOSE: Creates the complete BlockLand PostgreSQL schema from scratch.
//          This is the first migration — run on a fresh database.
//
// EXECUTION ORDER (dependency-safe):
//   1.  CREATE TYPE enums          — enums must exist before columns using them
//   2.  CREATE TABLE users         — no FK dependencies (self-ref handled last)
//   3.  CREATE TABLE roles         — no FK dependencies
//   4.  CREATE TABLE user_roles    — depends on users + roles
//   5.  CREATE TABLE auth_tokens   — depends on users
//   6.  CREATE TABLE properties    — depends on users
//   7.  CREATE TABLE property_documents — depends on properties + users
//   8.  CREATE TABLE transfers     — depends on properties + users
//   9.  CREATE TABLE ownership_records — depends on properties + users + transfers
//   10. CREATE TABLE transfer_approvals — depends on transfers + users
//   11. CREATE TABLE disputes      — depends on properties + users
//   12. CREATE TABLE dispute_evidence — depends on disputes + users
//   13. CREATE TABLE dispute_resolutions — depends on disputes + users
//   14. CREATE TABLE verification_logs — no FK dependencies
//   15. CREATE TABLE activity_logs  — depends on users
//   16. CREATE partial indexes      — added after all tables exist
//
// RUN:  npm run migration:run
// REVERT: npm run migration:revert
//
// GENERATED BY: TypeORM migration system (hand-crafted for dissertation clarity)
// =============================================================================

import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1700000000000 implements MigrationInterface {
  name = 'InitialSchema1700000000000';

  // ===========================================================================
  // UP — Apply the migration (create everything)
  // ===========================================================================
  public async up(queryRunner: QueryRunner): Promise<void> {

    // -------------------------------------------------------------------------
    // STEP 1: Create PostgreSQL ENUM types
    // Enums must be created before any table column references them.
    // IF NOT EXISTS guards against re-running on a partially-applied migration.
    // -------------------------------------------------------------------------

    await queryRunner.query(`
      CREATE TYPE user_role_enum AS ENUM (
        'REGISTRAR', 'OWNER', 'BUYER', 'PUBLIC', 'ADMIN'
      );
    `);

    await queryRunner.query(`
      CREATE TYPE property_status_enum AS ENUM (
        'ACTIVE', 'PENDING_TRANSFER', 'DISPUTED', 'INACTIVE'
      );
    `);

    await queryRunner.query(`
      CREATE TYPE land_size_unit_enum AS ENUM ('SQM', 'HECTARE', 'ACRE');
    `);

    await queryRunner.query(`
      CREATE TYPE zoning_type_enum AS ENUM (
        'RESIDENTIAL', 'COMMERCIAL', 'AGRICULTURAL', 'INDUSTRIAL'
      );
    `);

    await queryRunner.query(`
      CREATE TYPE file_type_enum AS ENUM ('PDF', 'JPG', 'PNG');
    `);

    await queryRunner.query(`
      CREATE TYPE acquisition_type_enum AS ENUM (
        'INITIAL_REGISTRATION', 'TRANSFER', 'DISPUTE_RESOLUTION'
      );
    `);

    await queryRunner.query(`
      CREATE TYPE transfer_status_enum AS ENUM (
        'PENDING_BUYER', 'PENDING_REGISTRAR', 'CONFIRMED', 'CANCELLED'
      );
    `);

    await queryRunner.query(`
      CREATE TYPE approver_role_enum AS ENUM ('BUYER', 'REGISTRAR');
    `);

    await queryRunner.query(`
      CREATE TYPE approval_action_enum AS ENUM ('APPROVED', 'REJECTED');
    `);

    await queryRunner.query(`
      CREATE TYPE dispute_type_enum AS ENUM (
        'OWNERSHIP_CLAIM', 'BOUNDARY_DISPUTE', 'FRAUD', 'OTHER'
      );
    `);

    await queryRunner.query(`
      CREATE TYPE dispute_status_enum AS ENUM (
        'OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED'
      );
    `);

    await queryRunner.query(`
      CREATE TYPE verification_query_type_enum AS ENUM (
        'PROPERTY_ID', 'TITLE_DEED', 'OWNER_ID'
      );
    `);

    await queryRunner.query(`
      CREATE TYPE verification_result_status_enum AS ENUM (
        'VERIFIED', 'MISMATCH', 'NOT_FOUND'
      );
    `);

    // -------------------------------------------------------------------------
    // STEP 2: users table
    // Core user record. No FK dependencies except on itself (no self-refs here).
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE users (
        id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
        full_name       VARCHAR(100)  NOT NULL,
        national_id     VARCHAR(20)   NOT NULL UNIQUE,
        email           VARCHAR(100)  NOT NULL UNIQUE,
        phone           VARCHAR(15)   NOT NULL,
        password_hash   VARCHAR(255)  NOT NULL,
        wallet_address  VARCHAR(50)   NULL,
        is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
        created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

        -- Field-level CHECK constraints
        CONSTRAINT CHK_users_full_name_length
          CHECK (char_length(full_name) >= 3),
        CONSTRAINT CHK_users_email_format
          CHECK (email ~* '^[^@]+@[^@]+\\.[^@]+$'),
        CONSTRAINT CHK_users_phone_format
          CHECK (phone ~ '^[0-9]{10,15}$'),
        CONSTRAINT CHK_users_wallet_format
          CHECK (wallet_address IS NULL OR wallet_address ~ '^S[PT][A-Z0-9]{38,39}$')
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_users_wallet ON users (wallet_address);`);

    // -------------------------------------------------------------------------
    // STEP 3: roles table
    // Lookup table for the 5 system roles. Seeded separately.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE roles (
        id          UUID               PRIMARY KEY DEFAULT gen_random_uuid(),
        name        user_role_enum     NOT NULL UNIQUE,
        description VARCHAR(200)       NULL,
        created_at  TIMESTAMPTZ        NOT NULL DEFAULT NOW(),
        updated_at  TIMESTAMPTZ        NOT NULL DEFAULT NOW()
      );
    `);

    // -------------------------------------------------------------------------
    // STEP 4: user_roles join table
    // Composite PK (user_id, role_id) — one user cannot have the same role twice.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE user_roles (
        user_id     UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        role_id     UUID          NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
        assigned_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

        PRIMARY KEY (user_id, role_id)
      );
    `);

    // -------------------------------------------------------------------------
    // STEP 5: auth_tokens table
    // Refresh token store for JWT rotation. Indexed for cleanup cron jobs.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE auth_tokens (
        id          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id     UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        token_hash  VARCHAR(255)  NOT NULL,
        expires_at  TIMESTAMPTZ   NOT NULL,
        revoked     BOOLEAN       NOT NULL DEFAULT FALSE,
        ip_address  VARCHAR(45)   NULL,
        created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_auth_tokens_user_id    ON auth_tokens (user_id);`);
    await queryRunner.query(`CREATE INDEX IDX_auth_tokens_expires_at ON auth_tokens (expires_at);`);

    // -------------------------------------------------------------------------
    // STEP 6: properties table
    // The central land record. All three blockchain fields are NOT NULL.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE properties (
        id                  UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
        plot_number         VARCHAR(20)             NOT NULL UNIQUE,
        title_deed_number   VARCHAR(30)             NOT NULL UNIQUE,
        address             VARCHAR(150)            NOT NULL,
        gps_lat             DECIMAL(10,7)           NULL,
        gps_lng             DECIMAL(10,7)           NULL,
        land_size           DECIMAL(12,4)           NOT NULL,
        unit                land_size_unit_enum     NOT NULL DEFAULT 'SQM',
        zoning_type         zoning_type_enum        NOT NULL,
        registration_date   DATE                    NOT NULL,
        status              property_status_enum    NOT NULL DEFAULT 'ACTIVE',
        token_id            VARCHAR(100)            NOT NULL UNIQUE,
        blockchain_tx_hash  VARCHAR(100)            NOT NULL,
        ipfs_hash           VARCHAR(100)            NOT NULL,
        notes               VARCHAR(500)            NULL,
        current_owner_id    UUID                    NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        created_by          UUID                    NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        created_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
        updated_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),

        CONSTRAINT CHK_properties_plot_length    CHECK (char_length(plot_number) >= 3),
        CONSTRAINT CHK_properties_address_length CHECK (char_length(address) >= 5),
        CONSTRAINT CHK_properties_land_size      CHECK (land_size > 0),
        CONSTRAINT CHK_properties_title_deed_len CHECK (char_length(title_deed_number) >= 5),
        CONSTRAINT CHK_properties_reg_date       CHECK (registration_date <= CURRENT_DATE)
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_properties_current_owner ON properties (current_owner_id);`);
    await queryRunner.query(`CREATE INDEX IDX_properties_status         ON properties (status);`);
    await queryRunner.query(`CREATE INDEX IDX_properties_token_id       ON properties (token_id);`);
    await queryRunner.query(`CREATE INDEX IDX_properties_blockchain_tx  ON properties (blockchain_tx_hash);`);

    // -------------------------------------------------------------------------
    // STEP 7: property_documents table
    // IPFS-linked supporting documents. Both ipfs_hash and file_hash are NOT NULL.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE property_documents (
        id              UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
        property_id     UUID             NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        uploaded_by     UUID             NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        file_name       VARCHAR(255)     NOT NULL,
        file_type       file_type_enum   NOT NULL,
        file_size_bytes INTEGER          NOT NULL,
        ipfs_hash       VARCHAR(100)     NOT NULL,
        file_hash       CHAR(64)         NOT NULL,
        uploaded_at     TIMESTAMPTZ      NOT NULL DEFAULT NOW(),

        CONSTRAINT CHK_prop_docs_file_size
          CHECK (file_size_bytes > 0 AND file_size_bytes <= 5242880)
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_prop_docs_property_id ON property_documents (property_id);`);
    await queryRunner.query(`CREATE INDEX IDX_prop_docs_uploaded_by ON property_documents (uploaded_by);`);
    await queryRunner.query(`CREATE INDEX IDX_prop_docs_ipfs_hash   ON property_documents (ipfs_hash);`);

    // -------------------------------------------------------------------------
    // STEP 8: transfers table
    // blockchain_tx_hash is nullable here — only populated on CONFIRMED status.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE transfers (
        id                  UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
        property_id         UUID                    NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
        seller_id           UUID                    NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        buyer_id            UUID                    NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        status              transfer_status_enum    NOT NULL DEFAULT 'PENDING_BUYER',
        initiated_at        TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
        confirmed_at        TIMESTAMPTZ             NULL,
        cancelled_at        TIMESTAMPTZ             NULL,
        sale_value          DECIMAL(15,2)           NULL,
        blockchain_tx_hash  VARCHAR(100)            NULL,
        notes               VARCHAR(500)            NULL,
        created_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
        updated_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),

        CONSTRAINT CHK_transfers_sale_value
          CHECK (sale_value IS NULL OR sale_value > 0)
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_transfers_property_id ON transfers (property_id);`);
    await queryRunner.query(`CREATE INDEX IDX_transfers_seller_id   ON transfers (seller_id);`);
    await queryRunner.query(`CREATE INDEX IDX_transfers_buyer_id    ON transfers (buyer_id);`);
    await queryRunner.query(`CREATE INDEX IDX_transfers_status      ON transfers (status);`);

    // -------------------------------------------------------------------------
    // STEP 9: ownership_records table
    // Transfer_id references transfers — created after transfers table.
    // blockchain_tx_hash is NOT NULL — every ownership change has an on-chain tx.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE ownership_records (
        id                  UUID                      PRIMARY KEY DEFAULT gen_random_uuid(),
        property_id         UUID                      NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
        owner_id            UUID                      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        transfer_id         UUID                      NULL REFERENCES transfers(id) ON DELETE SET NULL,
        acquired_at         TIMESTAMPTZ               NOT NULL,
        released_at         TIMESTAMPTZ               NULL,
        acquisition_type    acquisition_type_enum     NOT NULL,
        blockchain_tx_hash  VARCHAR(100)              NOT NULL,
        created_at          TIMESTAMPTZ               NOT NULL DEFAULT NOW(),
        updated_at          TIMESTAMPTZ               NOT NULL DEFAULT NOW()
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_ownership_property_id    ON ownership_records (property_id);`);
    await queryRunner.query(`CREATE INDEX IDX_ownership_owner_id       ON ownership_records (owner_id);`);
    await queryRunner.query(`CREATE INDEX IDX_ownership_prop_released  ON ownership_records (property_id, released_at);`);

    // PARTIAL INDEX: The most common query — find who currently owns a property.
    // WHERE released_at IS NULL filters to only active (current) ownership rows.
    // This makes "find current owner" O(1) even on tables with millions of records.
    // TypeORM @Index() does not support WHERE clauses — this must be in migration SQL.
    await queryRunner.query(`
      CREATE INDEX IDX_ownership_current
        ON ownership_records (property_id)
        WHERE released_at IS NULL;
    `);

    // -------------------------------------------------------------------------
    // STEP 10: transfer_approvals table
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE transfer_approvals (
        id              UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
        transfer_id     UUID                    NOT NULL REFERENCES transfers(id) ON DELETE CASCADE,
        approved_by     UUID                    NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        approver_role   approver_role_enum      NOT NULL,
        approved_at     TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
        action          approval_action_enum    NOT NULL,
        notes           VARCHAR(500)            NULL,
        created_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
        updated_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW()
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_transfer_approvals_transfer_id ON transfer_approvals (transfer_id);`);
    await queryRunner.query(`CREATE INDEX IDX_transfer_approvals_approved_by ON transfer_approvals (approved_by);`);

    // -------------------------------------------------------------------------
    // STEP 11: disputes table
    // blockchain_tx_hash is NOT NULL — every dispute must be flagged on-chain.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE disputes (
        id                  UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
        property_id         UUID                    NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
        raised_by           UUID                    NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        dispute_type        dispute_type_enum       NOT NULL,
        description         TEXT                    NOT NULL,
        status              dispute_status_enum     NOT NULL DEFAULT 'OPEN',
        raised_at           TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
        resolved_at         TIMESTAMPTZ             NULL,
        blockchain_tx_hash  VARCHAR(100)            NOT NULL,
        created_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
        updated_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),

        CONSTRAINT CHK_disputes_description_length
          CHECK (char_length(description) BETWEEN 20 AND 1000)
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_disputes_property_id ON disputes (property_id);`);
    await queryRunner.query(`CREATE INDEX IDX_disputes_status      ON disputes (status);`);
    await queryRunner.query(`CREATE INDEX IDX_disputes_raised_by   ON disputes (raised_by);`);

    // -------------------------------------------------------------------------
    // STEP 12: dispute_evidence table
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE dispute_evidence (
        id              UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
        dispute_id      UUID             NOT NULL REFERENCES disputes(id) ON DELETE CASCADE,
        uploaded_by     UUID             NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        file_name       VARCHAR(255)     NOT NULL,
        file_type       file_type_enum   NOT NULL,
        file_size_bytes INTEGER          NOT NULL,
        ipfs_hash       VARCHAR(100)     NOT NULL,
        file_hash       CHAR(64)         NOT NULL,
        uploaded_at     TIMESTAMPTZ      NOT NULL DEFAULT NOW(),

        CONSTRAINT CHK_dispute_evidence_file_size
          CHECK (file_size_bytes > 0 AND file_size_bytes <= 5242880)
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_dispute_evidence_dispute_id  ON dispute_evidence (dispute_id);`);
    await queryRunner.query(`CREATE INDEX IDX_dispute_evidence_uploaded_by ON dispute_evidence (uploaded_by);`);

    // -------------------------------------------------------------------------
    // STEP 13: dispute_resolutions table
    // UNIQUE constraint on dispute_id enforces the 1:1 relationship at DB level.
    // blockchain_tx_hash is NOT NULL — resolution requires on-chain confirmation.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE dispute_resolutions (
        id                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
        dispute_id          UUID          NOT NULL UNIQUE REFERENCES disputes(id) ON DELETE CASCADE,
        resolved_by         UUID          NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        resolution_notes    TEXT          NOT NULL,
        resolved_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        blockchain_tx_hash  VARCHAR(100)  NOT NULL
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_dispute_res_resolved_by ON dispute_resolutions (resolved_by);`);

    // -------------------------------------------------------------------------
    // STEP 14: verification_logs table
    // No FK dependencies — standalone audit table for public queries.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE verification_logs (
        id              UUID                              PRIMARY KEY DEFAULT gen_random_uuid(),
        query_type      verification_query_type_enum      NOT NULL,
        query_value     VARCHAR(100)                      NOT NULL,
        result_status   verification_result_status_enum   NOT NULL,
        queried_at      TIMESTAMPTZ                       NOT NULL DEFAULT NOW(),
        ip_address      VARCHAR(45)                       NULL
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_verification_queried_at  ON verification_logs (queried_at);`);
    await queryRunner.query(`CREATE INDEX IDX_verification_query_value ON verification_logs (query_value);`);
    await queryRunner.query(`CREATE INDEX IDX_verification_result      ON verification_logs (result_status);`);

    // -------------------------------------------------------------------------
    // STEP 15: activity_logs table
    // user_id is nullable — NULL for system-generated log entries.
    // metadata is JSONB — supports indexed queries on specific JSON keys.
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      CREATE TABLE activity_logs (
        id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id       UUID          NULL REFERENCES users(id) ON DELETE SET NULL,
        action        VARCHAR(100)  NOT NULL,
        entity_type   VARCHAR(50)   NOT NULL,
        entity_id     UUID          NOT NULL,
        metadata      JSONB         NULL,
        performed_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
      );
    `);

    await queryRunner.query(`CREATE INDEX IDX_activity_user_id      ON activity_logs (user_id);`);
    await queryRunner.query(`CREATE INDEX IDX_activity_entity        ON activity_logs (entity_type, entity_id);`);
    await queryRunner.query(`CREATE INDEX IDX_activity_performed_at  ON activity_logs (performed_at);`);
    await queryRunner.query(`CREATE INDEX IDX_activity_action        ON activity_logs (action);`);

    // GIN index on JSONB metadata — enables efficient queries like:
    //   WHERE metadata @> '{"blockchainTxHash": "0xabc..."}'
    await queryRunner.query(`
      CREATE INDEX IDX_activity_metadata_gin ON activity_logs USING GIN (metadata);
    `);

    // -------------------------------------------------------------------------
    // STEP 16: Seed the roles table (5 static rows — never changes)
    // -------------------------------------------------------------------------
    await queryRunner.query(`
      INSERT INTO roles (name, description) VALUES
        ('REGISTRAR', 'Land Officer — can register properties, approve transfers, manage disputes'),
        ('OWNER',     'Property Owner — can initiate transfers, view owned properties'),
        ('BUYER',     'Buyer — must approve a transfer directed to them'),
        ('PUBLIC',    'Public Viewer — read-only access to the verification portal'),
        ('ADMIN',     'System Administrator — can manage user accounts and registrar assignments')
      ON CONFLICT (name) DO NOTHING;
    `);
  }

  // ===========================================================================
  // DOWN — Revert the migration (drop everything in reverse dependency order)
  // ===========================================================================
  public async down(queryRunner: QueryRunner): Promise<void> {

    // Drop tables in reverse dependency order (children before parents)
    await queryRunner.query(`DROP TABLE IF EXISTS activity_logs CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS verification_logs CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS dispute_resolutions CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS dispute_evidence CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS disputes CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS transfer_approvals CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS ownership_records CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS transfers CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS property_documents CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS properties CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS auth_tokens CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS user_roles CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS roles CASCADE;`);
    await queryRunner.query(`DROP TABLE IF EXISTS users CASCADE;`);

    // Drop all enum types (must be after all tables that use them are dropped)
    await queryRunner.query(`DROP TYPE IF EXISTS verification_result_status_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS verification_query_type_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS dispute_status_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS dispute_type_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS approval_action_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS approver_role_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS transfer_status_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS acquisition_type_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS file_type_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS zoning_type_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS land_size_unit_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS property_status_enum;`);
    await queryRunner.query(`DROP TYPE IF EXISTS user_role_enum;`);
  }
}
